### ISSUE TITLE
Are these different than the live ones?

### ISSUE THREAD

**Issue by smileytechguy** [chubin/cheat.sheets#1]
For example, `cowsay` is on the site but not in the gh repo.

**Comment by chubin** [comment]
No, that is the same (live cheat.sh and cheat.sh on github).

cheat.sh uses many repositories, not only chubin/cheat.sheets.
That is an important feature of it!

Check README.md (#Cheat sheet sources)

**Comment by smileytechguy** [comment]
Ah, thanks

**Comment by dufferzafar** [comment]
So for cheatsheets that already exist on other repositories, we should update those?

And the ones that don't exist on other repos, we should create a new one here.

Right?

**Comment by chubin** [comment]
@dufferzafar Yes
