### ISSUE TITLE
🍃 Add Spring Boot CLI (spring)

### ISSUE THREAD

**Issue by TGotwig** [chubin/cheat.sheets#174]
There could be something for [Spring Boot CLI](https://docs.spring.io/spring-boot/docs/current/reference/html/cli.html), so `cheat.sh/spring`, I think I could take a look into it 😼🔎

**Comment by chubin** [comment]
It would be great. Do we want to (1) add only one cheat sheet for the cli tool `spring` or (2) do we want to map the whole spring help to cheat.sh? Probably we should start from (1)?

**Comment by TGotwig** [comment]
Added something small first, so (1) 😇
