### ISSUE TITLE
Add i3 cheatsheet

### ISSUE THREAD

**Issue by SoptikHa2** [chubin/cheat.sheets#85]
What about adding i3 cheatsheet? I can write it and send pull request if you want to.

**Comment by terminalforlife** [comment]
That sounds awesome. I mean i3-wm. I'd love to add to that as well.

**Comment by chubin** [comment]
@SoptikHa2 Sure! It would be really great if you could add such cheat sheets. Fully agree with @terminalforlife 
If you need any help from our side, just give a sign

**Comment by SoptikHa2** [comment]
Created pull request.

I included basic hotkeys and short guide about positioning windows with containers. Tell me if you have more ideas.

I'm not sure how good will the keybindings look like when highlighted so it might be needed to be adjusted.

I'd be grateful for any suggestions and edits. English isn't my mother language so I expect multiple mistakes.

**Comment by chubin** [comment]
Please take a look:
```
curl cht.sh/i3
```

In my opinion it looks pretty good; maybe only just some information about i3 configuration should be added
